### ISSUE TITLE
MiBIG

### ISSUE THREAD

**Issue by sdrogers** [sdrogers/nplinker#1]
These should be loaded in as MiBIG BCG objects at the start....and then placed into the GCFs rather than making them again during the loading process.

**Comment by andrewramsay** [comment]
Should be resolved in current version, MiBIG BGC objects are only created once in [make_mibig_bgc_dict](https://github.com/sdrogers/nplinker/blob/66eecce3b8274a80e0e2d0537e4ab9d683fbdbd2/prototype/nplinker/genomics.py#L399)
