### ISSUE TITLE
Remove strain assignment from BGC loaders?

### ISSUE THREAD

**Issue by CunliangGeng** [sdrogers/nplinker#104]
Strain object is initiated and assigned to BGC object in BGC loaders, like `MibigBGCLoader` and `AntismashBGCLoader`.
It makes more sense to init strain objects and assign it to BGC outside of BGC loaders.

- [x] check the logics of strain loading
- [x] check the assignment of strain to BGC, spec and other objects
- [x] assign strain to BGC outside of BGC loaders.

To solve this issue after refactoring of strain mapping loading and GCF loading.

**Comment by hechth** [comment]
The strain objects in form of a `StrainCollection` are also passed to the metabolomics loading - I think it makes sense to load the strains afterwards and then add them after loading the metabolomics and genomics seperately.

**Comment by CunliangGeng** [comment]
Solved in #197.
