### ISSUE TITLE
Implement GNPS loading functionality on `DatasetLoader` layer

### ISSUE THREAD

**Issue by hechth** [sdrogers/nplinker#107]
The GNPS loading functionality is implemented for all the parts but not on the layer where it could replace the `load_dataset` function or `_load_metabolomics` - we have to decide where to put this functionality and implement the proper class(es).

This would mean replacing the `load_gnps.py` and `metabolomics.py` files with the `GNPSLoader` class.

The `GNPSLoader` should take all the paths as optional arguments so the user can specify them and if they are not there.

The init function basically has 2 options, either take the root to the folder and figure out the paths yourself or take all individual paths loaded from the config and load the data.

**Comment by CunliangGeng** [comment]
This is solved in a different way in #196.
