### ISSUE TITLE
Hardware Requirements:

### ISSUE THREAD

**Issue by ialas** [sdrogers/nplinker#124]
Hi, I'm working with our IT department to setup a local linux virtual machine to run nplinker, as previous attempts to use WSL with the web-app have run into issues.

Could I get clarification on the exact specific hardware requirements for NPLinker?

Thank you!

**Comment by CunliangGeng** [comment]
If you're using Linux system then NPLinker should work well. There is no special hardware requirements for Linux system.

You can find more details in the [README](https://github.com/NPLinker/nplinker) about supported OS.

**Comment by justinjjvanderhooft** [comment]
Exactly, I think having a decent amount of memory helps if you want to run larger paired omics data experiments. Some decencies like BiG-SCAPE have increasing memory wishes with larger amount of mined gene clusters. Hence, it will mainly depend on the input datasets....
