### ISSUE TITLE
nplinker library download

### ISSUE THREAD

**Issue by MenusGarg** [sdrogers/nplinker#128]
install-nplinker-deps
✅ NPLinker dependecies and databases will be installed in: /home/streptomyces/nplinker-webapp/env/nplinker_lib
⏳ Installation will take about 5 minutes

✅ Package manager is 'apt'

Hello developers!
I am not sure why there is no file/folder getting downloaded in my nplinker_lib after following instructions as per given. It is finishing in few seconds and doesn't give anything. please can you assist me.

Thank you
Menus Garg

**Comment by CunliangGeng** [comment]
Hi Menus, thanks for using NPLinker.

Based on the log info, you must be using Linux.  Is there any more log info after `✅ Package manager is 'apt'`? 
If not, there might be some problem on running this command on your machine:
https://github.com/NPLinker/nplinker/blob/df8b7b599bb134aa0c50119d5f2df7c3b99e90b3/bin/install-nplinker-deps#L60

You could try to run `apt update` manually to see if it works or not.

**Comment by hechth** [comment]
I also had the same issue with sudo - when cloning the repo, I had to change one apt-get install to sudo apt-get install and then sudo the whole script if I remember it correctly.

**Comment by MenusGarg** [comment]
It worked as I added install-nplinker-deps --run-on-github while running it. 

Thank you.

**Comment by CunliangGeng** [comment]
Great! I'm closing the issue then. You can reopen it if you have more questions.
