### ISSUE TITLE
Exception: Failed to find *ANY* strains, missing strain_mappings.csv?

### ISSUE THREAD

**Issue by MenusGarg** [sdrogers/nplinker#130]
Hi,
I am trying to run nplinker using docker. I have given strain_mapping.csv as per instructions (image attached) and similar dataset had been used to run before as it is. the same dataset which was successfully run before is also giving same error. 

It is constantly giving this error:

**Exception: Failed to find *ANY* strains, missing strain_mappings.csv?**

![Screenshot from 2023-03-21 13-53-45](https://user-images.githubusercontent.com/105439696/226674957-41e8c534-0cf7-491d-8102-a98b3314778c.png)

Any suggestions? It will be great if you resolve the issue.

Thank you
Menus Garg

**Comment by CunliangGeng** [comment]
I guess you are giving your own data (BGC and MS) to NPLinker. If it's true, then you need to create the `strain_mapping.csv` to build the shared strain name between BGC and MS.

For that, the first column must be the unique strain name. Then you need to put the BGC file names and MS file names to the other columns.

For example, if your BGC file is `NZ_AZWU01000023.region002.gbk` and MS file is `12c.mzXML`, and they are from the strain `Salinispora arenicola  CNT005`, then the `strain_mapping.csv` will look like:

`Salinispora arenicola  CNT005,NZ_AZWU01000023.region002,12c.mzXML`

If you have more BGC and MS from the same strain, then you need to add them to the next columns.
