### ISSUE TITLE
Use UUID for singleton molecular family?

### ISSUE THREAD

**Issue by CunliangGeng** [sdrogers/nplinker#144]
The issue is created from  https://github.com/NPLinker/nplinker/pull/142#discussion_r1203825955

> The -1 ID somewhat represents an unknown family or singleton family - all of these will have the same id, which is in conflict with the idea of having unique string id's for every object.
> Given the id in the GNPS output is -1, do we want to configure a UUID as ID to be able to distinguish the singletons?

- [x] check the influence of using UUID, e.g. how to verify the singletons
- [x] if feasible, using [UUID](https://docs.python.org/3/library/uuid.html) for singletons

- [x] does it make sense to use UUID for all types of MFs? not for now.

**Comment by hechth** [comment]
I'd be in favour of UUIDs for singleton families - or maybe even all families?

**Comment by CunliangGeng** [comment]
The current family id looks good enough to support the features of nplinker right now. I'd like to keep it as it is until we see  requirements for uuid.
