### ISSUE TITLE
Refactor `DatasetLoader` class 

### ISSUE THREAD

**Issue by gcroci2** [sdrogers/nplinker#145]
We will more tasks in this issue in the near future. 

- [ ] Since the download and run logics should be independent, we should move `run_bigscape` out of `PODPDownloader` to an higher level, for example to the loader.py module.
  - Right now `run_biscape` is defined in pairedomics/runbigscape.py, and it's used in `podp_run_bigscape`, called in pairedomics/downloader.py.

**Comment by CunliangGeng** [comment]
Merge this issue to #115.
