### ISSUE TITLE
Discard single-BGC GCF and single-spectrum molecular family?

### ISSUE THREAD

**Issue by CunliangGeng** [sdrogers/nplinker#175]
### Definitions:

- **single-BGC GCF**: a GCF consisting of only one BGC
- **single-spectrum molecular family(MF)**: a molecular family consisting of only one spectrum

### Question:
The single-BGC GCFs and single-spectrum MFs seem not necessary in NPLinker (scoring). If we don't consider these GCFs and MFs, we don't need to load them from files to python objects at all, which will help simplify the logics of data loading, extracting and scoring, saving more memory and running faster.

So shall we discard them in NPLinker? @justinjjvanderhooft 

The following figure may help to think about this question:
![image](https://github.com/NPLinker/nplinker/assets/9798985/2c1e59aa-b073-4ffb-942e-181c1ca5f5da)

**Comment by justinjjvanderhooft** [comment]
Whilst I understand the reasoning behind, I would favour to include the singletons from both genomics and metabolomics during initial loading. After loading, we could add an option to remove singletons from genomics, from metabolomics, or from both omics [to speed up analytics]. The main reason to keep them included is that they are sometimes the interesting/relevant signals and they can be scored (as they can be present in a subset of the strains/samples).

**Comment by CunliangGeng** [comment]
what do you mean that they can be present in a subset of the strains/samples? do you mean the target strains (e.g. user specified strains)?

Besides using the singletons for scoring, do you have other needs?

**Comment by justinjjvanderhooft** [comment]
what do you mean that they can be present in a subset of the strains/samples? do you mean the target strains (e.g. user specified strains)? --> yes, just like the GCFs or MFs, singletons have the property to be present in 1 to all of the strains/samples in the user provided data.

Besides using the singletons for scoring, do you have other needs? --> besides adding/keeping the annotations like for the other data, not I think.

**Comment by CunliangGeng** [comment]
Thanks for the comments! So the conclusion is to keep the singletons and to treat them the same way as other GCFs or MFs.

I'm closing this issue. Please reopen it if needed.
