### ISSUE TITLE
Running NPLinker tutorial

### ISSUE THREAD

**Issue by davidkubanek** [sdrogers/nplinker#213]
I put together a setup tutorial that makes NPLinker work for me. There are edge cases that I am trying to fix if they arise but this should be a good start:
https://novogaia.notion.site/Running-NPLinker-11cb0ca46ca149a3a28cf56cb90be74d

**Comment by CunliangGeng** [comment]
Thanks David. As what I have told you in the email that we're refactoring the data preparation part of nplinker. Actually I have finished the coding this week for that and now is adding tests to make sure it work as expected. The code will be submitted for review in coming days. After the PR is merged to dev branch, it's then ready for you to try the new way of interacting with nplinker.

Our 2nd community meeting will be on next Tuesday 2024-03-05 16:00 - 17:00. I will give an update about the progress. You're very welcome to join.  

Here is the [Teams meeting link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2MzOTY5MjItOTRmOS00MjAzLTg0NmItN2ZhYjRkYTc3MGYy%40thread.v2/0?context=%7b%22Tid%22%3a%22aa3aeacc-6307-42b2-ac05-787dd5c32574%22%2c%22Oid%22%3a%22a2ff051f-3861-4695-8db8-f1591fa5b36d%22%7d)
Meeting ID: 333 693 229 29
Passcode: TWi6Mz

For the former community meetings, you can find the slides on https://github.com/NPLinker/materials4community.

**Comment by davidkubanek** [comment]
Hi, great! I will see if I can make the meeting but would be nice to join. Good luck with the code.:)

**Comment by CunliangGeng** [comment]
@davidkubanek I just released the tutorials for the latest version of nplinker, please take a look https://nplinker.github.io/nplinker/latest/.

If you have any comments about it, please go this issue https://github.com/NPLinker/nplinker/issues/232.

I'm closing this issue now.
