### ISSUE TITLE
Data size warnings / checks when installing and using nplinker package

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/nplinker#237]
It would be good to think about how to warn / validate the size required on the user's drive to install and run nplinker, especially when large(r) amount of data is selected for downloading, also considering that additional space will be needed to store (in-between and end) processed results. A check on available disk space versus estimated download size when starting the data download in PoDP mode could be useful - and some instructions in the documentation. Let's discuss further in a future meeting :-)

**Comment by CunliangGeng** [comment]
Thought the discussion in the community meeting, we decided to do the following:
1. Add information to the documentation about the required disk space for installing nplinker
2. Implement code to check the availability of disk space before downloading. If the available disk space is smaller than a cutoff value (say 10GB), raise a warning and ask user if he wants to continue or not.
