### ISSUE TITLE
NP-optimised Metcalf score crashes

### ISSUE THREAD

**Issue by grimur** [sdrogers/nplinker#24]
I was playing around with the Metcalf scoring, and it seems that the NP-optimised version is broken.

Running `metcalf_scoring` on a particular MF and GCF works, while running `metcalf_scoring_np` on a the same pair gives the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-96-acda90509165> in <module>()
----> 1 print(scoring.metcalf_scoring_np(spectra_families[0], gcf_list[0], strain_list, False))
      2 
      3 print numpy.log(0.007)
      4 print numpy.log(0.3)

/home/grimur/git/nplinker/nplinker/prototype/scoring.pyc in metcalf_scoring_np(spectral_like, gcf_like, strains, do_random, weights)
    171     # of them by 2 and adding together will give a new array containing values in
    172     # the range 0-3: 0 = neither, 1 = GCF only, 2 = spectrum only, 3 = both
--> 173     result = (2 * spectral_like.strains_lookup) + gcf_like.strains_lookup
    174 
    175     # use bincount to total up the number of occurrences of each value in result,

AttributeError: 'MolecularFamily' object has no attribute 'strains_lookup'
```

**Comment by andrewramsay** [comment]
The metcalf_scoring_np method is an old one that just hasn't been removed yet, and never supported MFs properly - Florian's implementation in data_linking.py is much faster and should handle the different combinations of objects too. To do the same thing with it you'd have to create an NPLinker object from whatever dataset you're using, call .process_dataset() to generate the scores, and then use .get_links() to retrieve the results for the object you're interested in. 

I've got a batch of commits I haven't pushed yet which make a lot of updates to the way the scoring code works, and also gets rid of the leftover metcalf methods from scoring.py. I still have a few things to finish but I'll try to push everything later on today sometime, along with a new notebook with some examples using the new API.

**Comment by grimur** [comment]
Ah, ok. Never mind about this, then. Sorry about that, closing the issue.
