### ISSUE TITLE
Podp: not all genome IDs are in antismashDB

### ISSUE THREAD

**Issue by liannette** [sdrogers/nplinker#242]
In podp mode, the genome RefSeq IDs are used to download the antismash results from antismashDB. 
However, not all RefSeq genomes are in antismashDB, leading to an incomplete dataset.

Suggestion:
Check whether all genomes could be downloaded from antismashDB, and if not, output a message that the missing antimash results need to be manually added before continuing the script.

**Comment by CunliangGeng** [comment]
Will add a log message (Warning) to report the missing antismash results
