### ISSUE TITLE
Select subset of the data

### ISSUE THREAD

**Issue by gcroci2** [sdrogers/nplinker#265]
Once I've generated the data by following the [quickstart](https://nplinker.github.io/nplinker/latest/quickstart/#4-run-nplinker), I need to select a subset of them for testing purposes:

```python
import pickle

with open('output/npl.pkl', 'rb') as f:
    data = pickle.load(f)
bgcs, gcfs, spectra, mfs, strains, links = data

# select subset for bgcs, gcfs, spectra, mfs
bgcs_selected = bgcs[0:10]
gcfs_selected = gcfs[0:10]
spectra_selected = spectra[0:10]
mfs_selected = mfs[0:10]
# select subset for strains
strains_list = [strain for strain in strains]
strains_set = set(strains_list[0:10])
strains.filter(strains_set)
```

- Could it be a useful addition to give the possibility to filter via indexes the strains as well? As we do for the rest. 
- For the links, I didn't figure out a way for selecting a subset - and they are the heaviest part of the .pkl file, of course. I tried the following but it gives me `TypeError: LinkGraph.add_link() takes 3 positional arguments but 4 were given`:

```python
from nplinker.scoring import LinkGraph

selected_links = links.links[0:100]

lg_selected = LinkGraph()
for i in range(len(selected_links)):
    lg_selected.add_link(selected_links[i][0], selected_links[i][1], selected_links[i][2]['metcalf'])

```

---

Action points
- [ ] implement the `filter` method for LinkGraph:  `lg1 = links.filter(gcfs, spectra)`

**Comment by CunliangGeng** [comment]
> Could it be a useful addition to give the possibility to filter via indexes the strains as well? As we do for the rest.

It's possible. But why do you need to select subset of strains? Note that the `bgcs_selected` you got might have strains that are not present in the subset of the strains.

**Comment by gcroci2** [comment]
We decided to proceed with creating a filtering method in the `LinkGraph` class for filtering nodes given as input selected entities.
