### ISSUE TITLE
Restrict NPLinker strain object to data set population

### ISSUE THREAD

**Issue by grimur** [sdrogers/nplinker#27]
At the moment, the NPLinker object strain collection contains all known strains. It should only contain those strains belonging to the current data set.

**Comment by andrewramsay** [comment]
so after loading all the data files and assigning strains to objects, any strains that were **not** assigned to an object should be removed from the overall nplinker "strains" list? i can make that change pretty easily if you're busy on other things?

**Comment by andrewramsay** [comment]
looks like you already fixed it in 43fa0dfad2d31a72e7e34e2ca1146044463e9847 ?
