### ISSUE TITLE
Incorrect precursor m/z when loading MGF file from GNPS

### ISSUE THREAD

**Issue by liannette** [sdrogers/nplinker#282]
When loading the MGF file into Spectrum object, the m/z of the precursor ion is imported/calculated incorrectly.

In the MGF file, the "pepmass" of a spectrum/feature is given. Currently, this pepmass is divided by the ion charge to calculate the precursor m/z.

However, this step is unnecessary. The pepmass value is equivalent to the precursor m/z value, they are just two different terms for the same thing - the m/z of the ion selected for fragmentation.

**Comment by liannette** [comment]
@CunliangGeng I don't think that I can assign this issue to myself, can you do it?

**Comment by justinjjvanderhooft** [comment]
@liannette I did it....

**Comment by CunliangGeng** [comment]
> However, this step is unnecessary. The pepmass value is equivalent to the precursor m/z value, they are just two different terms for the same thing - the m/z of the ion selected for fragmentation.

From the https://www.matrixscience.com/help/data_file_help.html#GEN, what I got is that `PEPMASS` is peptide mass but not m/z. They may have same values but we should treat them separately in the code. Are you sure we should use pepmass for m/z? If so, you have to give your comments in the code to make it clear.

**Comment by liannette** [comment]
Dora realized that the m/z values were off when she was analyzing her experimental data. I agree that the website you mention seems to support your point. However, on this site (https://www.matrixscience.com/help/obsolete_data_file_formats.html) they are elaborating on the `PEPMASS` value in more detail, and it really seems to be refering to the precursor ion m/z:

> In Mascot generic format, the precursor peptide mass is an observed m/z value, from which Mr or MHnn+ is calculated using the prevailing charge state. For example, in Mascot:
> 
> PEPMASS=1000
> CHARGE=2+
> 
> … means that the relative molecular mass Mr is 1998.

**Comment by justinjjvanderhooft** [comment]
These terms are confusing indeed. I can confirm that, in the case of these MGF files, the PEPMASS is the same as the m/z.

**Comment by CunliangGeng** [comment]
Thank you guys for clarifying it. @liannette  Could you add a comment in your PR to mention the source/fact?

**Comment by liannette** [comment]
I did that 👌
