### ISSUE TITLE
Replace square NPLinker logo by one used for Slack (with NPLinker text)

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/nplinker#288]
![NPLinker_slack_icon](https://github.com/user-attachments/assets/cf269d35-dfd6-4692-b2aa-4c2525e45d92)

**Comment by CunliangGeng** [comment]
Do you mean replace the logo for the github?

**Comment by justinjjvanderhooft** [comment]
Looking now, I see that this logo was used, so looks to be fine - closing the issue!

**Comment by justinjjvanderhooft** [comment]
I meant everywhere where we use the squared version of the logo, let's use the one above!
