### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by justinjjvanderhooft** [sdrogers/nplinker#48]
Unless I overlook things, I don't see a licence associated to the NPLinker software yet. I would be good to have one, for example the Apache License 2.0

**Comment by andrewramsay** [comment]
OK, for the moment I've added an Apache 2.0 LICENSE file in 8a767e87e84157b778d8d17a27af84b66d1e5d05, that should be picked up and highlighted by GitHub automatically when someone browses the repository here.

If everyone's happy with this license I can add the indicated copyright text from the license to each source file as well.

**Comment by justinjjvanderhooft** [comment]
Thanks Andrew - fine with me, I guess Kate and Simon are ones to further confirm this.... :-)

**Comment by andrewramsay** [comment]
@sdrogers any objections? 

I'll email Kate and check with her.

**Comment by sdrogers** [comment]
I think we probably ought to have one to meet the BBSRC requirement of all code being open source.

I don’t know anything about the pros and cons of the different licenses? Can you comment on why Apache 2.0?

**Comment by justinjjvanderhooft** [comment]
Tjis is the recommended one by the Netherlands eScienceCenter....that is why I suggested it, I don't have a personal preference.... It fits with open science etc.

**Comment by andrewramsay** [comment]
OK, after a quick discussion with Kate, remaining actions then are:

 * create an "AUTHORS" file in the repository where we'll list all contributor names
 * add the Apache 2.0 header to all the source code files with the text "Copyright 2021 The NPLinker Authors"

I'll do that later today at some point and close this issue when it's done.

**Comment by andrewramsay** [comment]
I've now added the license header to all the .py files in the prototype/nplinker folder, and created the AUTHORS file with a list of contributors to date (feel free to edit if I missed anyone!)

**Comment by justinjjvanderhooft** [comment]
Thanks Andrew!
