### ISSUE TITLE
Error in loading from PoDP: MSV000078839

### ISSUE THREAD

**Issue by louwenjjr** [sdrogers/nplinker#58]
Hey Andrew,

I had an issue with loading dataset MSV000078839 from PoDP using the docker version of NPLinker. When trying another PoDP dataset this worked out fine, and I also tried the previous docker image version which produced the same error. Any idea what is going on?

Thanks! :)

This is the log and error that i get:
Warning: plotting functionality will not be available (missing matplotlib and/or seaborn)
2021-11-26 14:29:48,894 Watching: /app/nplinker/webapp/npapp/theme.yaml
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/static/css/ChemDoodleWeb.css
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/static/css/npapp.css
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/static/css/bootstrap.min.css
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/templates/tmpl.onclick.py.html
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/templates/tmpl.basic.py.html
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/templates/index.html
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/templates/tmpl.basic.search.py.html
2021-11-26 14:29:48,895 Watching: /app/nplinker/webapp/npapp/templates/tmpl.onclick.search.py.html
2021-11-26 14:29:48,895 Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
2021-11-26 14:29:48,897 User authentication hooks NOT provided (default user enabled)
2021-11-26 14:29:48,902 Bokeh app running at: http://localhost:5006/npapp
2021-11-26 14:29:48,902 Starting Bokeh server with process id: 1
on_server_loaded
DATAPATH: /data/nplinker.toml
14:29:48 [DEBUG] config.py:86, Parsing default config file: /data/.config/nplinker/nplinker.toml
14:29:48 [DEBUG] config.py:89, Loading user config /data/nplinker.toml
14:29:48 [INFO] config.py:117, Selected platform project ID MSV000078839
14:29:48 [INFO] downloader.py:161, Downloader for MSV000078839, caching to /data/nplinker_data/pairedomics
14:29:48 [INFO] downloader.py:164, Downloading new copy of platform project data...
14:29:49 [INFO] downloader.py:190, Found project, retrieving JSON data...
14:29:49 [INFO] downloader.py:215, Going to download the metabolomics data file
14:29:49 [INFO] downloader.py:595, Downloading metabolomics data from https://gnps.ucsd.edu/ProteoSAFe/DownloadResult?task=840eadb054f74d74ae42152a08ed9628&view=download_clustered_spectra
14:29:55 [INFO] downloader.py:607, Downloaded metabolomics data!
14:29:55 [INFO] downloader.py:612, Extracting files to /data/nplinker_data/pairedomics/extracted/MSV000078839
14:29:57 [INFO] downloader.py:637, Found OLD GNPS structure
14:29:57 [INFO] downloader.py:351, Checking for antismash data 1/39, current genome ID=GCA_000377965.1
14:29:57 [INFO] downloader.py:366, Beginning lookup process for genome ID GCA_000377965.1
14:29:57 [INFO] downloader.py:249, Attempting to resolve RefSeq accession from Genbank accession GCA_000377965.1
14:29:58 [WARNING] downloader.py:284, Failed resolving GenBank accession gca_000377965.1, error Server disconnected without sending a response.
14:29:58 [WARNING] downloader.py:373, Failed lookup for genome ID GCA_000377965.1
14:29:58 [INFO] downloader.py:351, Checking for antismash data 2/39, current genome ID=GCA_000365385.1
14:29:58 [INFO] downloader.py:366, Beginning lookup process for genome ID GCA_000365385.1
14:29:58 [INFO] downloader.py:249, Attempting to resolve RefSeq accession from Genbank accession GCA_000365385.1
14:29:58 [WARNING] downloader.py:284, Failed resolving GenBank accession gca_000365385.1 , error Server disconnected without sending a response.
14:29:58 [WARNING] downloader.py:373, Failed lookup for genome ID GCA_000365385.1
14:29:58 [INFO] downloader.py:351, Checking for antismash data 3/39, current genome ID=GCA_000377525.1
14:29:58 [INFO] downloader.py:366, Beginning lookup process for genome ID GCA_000377525.1
14:29:58 [INFO] downloader.py:249, Attempting to resolve RefSeq accession from Genbank accession GCA_000377525.1
14:29:59 [WARNING] downloader.py:284, Failed resolving GenBank accession gca_000377525.1 , error 'NoneType' object has no attribute 'findChildren'
14:29:59 [WARNING] downloader.py:373, Failed lookup for genome ID GCA_000377525.1
14:29:59 [INFO] downloader.py:351, Checking for antismash data 4/39, current genome ID=GCA_000514715.1
14:29:59 [INFO] downloader.py:366, Beginning lookup process for genome ID GCA_000514715.1
14:29:59 [INFO] downloader.py:249, Attempting to resolve RefSeq accession from Genbank accession GCA_000514715.1
14:30:01 [WARNING] downloader.py:284, Failed resolving GenBank accession gca_000514715.1, error 'NoneType' object has no attribute 'findChildren'
14:30:01 [WARNING] downloader.py:373, Failed lookup for genome ID GCA_000514715.1
14:30:01 [INFO] downloader.py:351, Checking for antismash data 5/39, current genome ID=GCA_000527195.1
14:30:01 [INFO] downloader.py:366, Beginning lookup process for genome ID GCA_000527195.1
14:30:01 [INFO] downloader.py:249, Attempting to resolve RefSeq accession from Genbank accession GCA_000527195.1
14:30:02 [WARNING] downloader.py:284, Failed resolving GenBank accession gca_000527195.1 , error Server disconnected without sending a response.
14:30:02 [WARNING] downloader.py:373, Failed lookup for genome ID GCA_000527195.1
14:30:02 [INFO] downloader.py:351, Checking for antismash data 6/39, current genome ID=GCA_000424825.1
14:30:02 [INFO] downloader.py:366, Beginning lookup process for genome ID GCA_000424825.1
14:30:02 [INFO] downloader.py:249, Attempting to resolve RefSeq accession from Genbank accession GCA_000424825.1
14:30:03 [WARNING] downloader.py:284, Failed resolving GenBank accession gca_000424825.1 , error 'NoneType' object has no attribute 'findChildren'
14:30:03 [WARNING] downloader.py:373, Failed lookup for genome ID GCA_000424825.1
14:30:03 [INFO] downloader.py:351, Checking for antismash data 7/39, current genome ID=2526164782
14:30:03 [INFO] downloader.py:366, Beginning lookup process for genome ID 2526164782
14:30:06 [WARNING] downloader.py:373, Failed lookup for genome ID 2526164782
14:30:06 [INFO] downloader.py:351, Checking for antismash data 8/39, current genome ID=None
14:30:06 [INFO] downloader.py:366, Beginning lookup process for genome ID None
14:30:06 [WARNING] downloader.py:321, Unable to resolve genome_ID: {'genome_type': 'genome'}
14:30:06 [WARNING] downloader.py:373, Failed lookup for genome ID None
2021-11-26 14:30:06,256 Error in server loaded hook TypeError('sequence item 0: expected str instance, NoneType found',)
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/contexts.py", line 173, in run_load_hook
    self._application.on_server_loaded(self.server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/application.py", line 186, in on_server_loaded
    h.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/directory.py", line 232, in on_server_loaded
    return self._lifecycle_handler.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/lifecycle.py", line 75, in on_server_loaded
    return self._on_server_loaded(server_context)
  File "/app/nplinker/webapp/npapp/server_lifecycle.py", line 58, in on_server_loaded
    nh.load()
  File "/app/nplinker/webapp/npapp/server_lifecycle.py", line 22, in load
    self.load_nplinker()
  File "/app/nplinker/webapp/npapp/server_lifecycle.py", line 41, in load_nplinker
    if not self.nplinker.load_data():
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/nplinker.py", line 256, in load_data
    self._loader.validate()
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/loader.py", line 160, in validate
    self._downloader.get(self._docker.get('run_bigscape', self.RUN_BIGSCAPE_DEFAULT), self._docker.get('extra_bigscape_parameters', self.EXTRA_BIGSCAPE_PARAMS_DEFAULT))
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/pairedomics/downloader.py", line 218, in get
    self._download_genomics_data(self.project_json['genomes'])
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/pairedomics/downloader.py", line 375, in _download_genomics_data
    f.write(genome_obj.to_csv()+'\n')
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/pairedomics/downloader.py", line 70, in to_csv
    return ','.join([self.original_id, str(self.resolved_id), str(self.attempted), self.filename])
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by andrewramsay** [comment]
From a quick look I think all the WARNING messages are because the hacky NCBI website parsing that downloader.py does is broken, I guess because they've updated their site recently. I'll check if I can find an easy way to get it working again. 

The TypeError it finally crashes at is a consequence of the first problem, it's trying to write out a string that is actually `None` and crashing because it assumed it would never be `None` at that point, but it is because the parser is broken!

**Comment by andrewramsay** [comment]
I ended up rewriting the NCBI GenBank to RefSeq lookup in a way that seems to get it working again, plus a few other bugfixes and improvements. You can try it out by pulling the latest (v1.1.3) Docker image, should be available now.

Using that it seems to be able to resolve almost all of the genome records here and downloads 26/39 from antiSMASH successfully. 

-------

This wasn't causing any of the original problems, but is there anything we can do with genome records that don't have a RefSeq, GenBank or JGI genome ID field? There's one in this dataset:

> {"genome_ID": {"genome_type": "genome"}, "genome_label": "Streptomyces sp. CNQ149", "BioSample_accession": "1649593 "}

**Comment by louwenjjr** [comment]
Thanks for solving the issue!

I think you would need to link the biosample accession to nucleotide in NCBI for example to retrieve GenBank/RefSeq accession. I think also in this particular case the accession is wrong for this strain as that biosample accession points to a human project, so I made an issue on the PoDP github.

**Comment by justinjjvanderhooft** [comment]
@louwenjjr - you could also update the project yourself by clicking on "edit" and make the necessary change(s) - and resubmit the project. Thx!
