### ISSUE TITLE
MiBIG v3.x support

### ISSUE THREAD

**Issue by andrewramsay** [sdrogers/nplinker#94]
See [this issue](https://github.com/NPLinker/nplinker-webapp/issues/13).

[This helper method](https://github.com/NPLinker/nplinker/blob/main/src/nplinker/pairedomics/downloader.py#L78) can cause problems since the v3.x MiBIG JSON format has apparently changed again vs 2.x and 1.x. 

So if someone uses the default version (currently still 1.4) and extra BGCs are retrieved separately using `download_mibig_bgc_json`, it can result in a mix of 1.4 and 3.x formats in the local `mibig_json` folder.

That then causes an exception in [this method](https://github.com/NPLinker/nplinker/blob/main/src/nplinker/genomics/genomics.py#L358) because it currently assumes anything that isn't v1.x format must be v2.x. 

If support for the MiBIG 3.x JSON format is added to `genomics.py` it should allow it to handle a mix of different versions. 

---

It might also be sensible to update the default version from 1.4 to 2.0?

**Comment by hechth** [comment]
@CunliangGeng I think this is already handled in the development version?

**Comment by CunliangGeng** [comment]
Yep, this issue is already solved in dev version, the default version of mibig has been updated to latest v3.1.
